# Generated by Django 4.2.27 on 2025-12-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده'), ('returned', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('address_title', models.CharField(max_length=50, verbose_name='عنوان آدرس')),
                ('address_province', models.CharField(max_length=50, verbose_name='استان')),
                ('address_city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address_full', models.TextField(verbose_name='آدرس کامل')),
                ('address_postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='تلفن گیرنده')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع کل')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ تخفیف')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف استفاده شده')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('shipping_method', models.CharField(blank=True, max_length=50, verbose_name='روش ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد رهگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='هزینه')),
                ('min_delivery_days', models.PositiveSmallIntegerField(default=1, verbose_name='حداقل روز ارسال')),
                ('max_delivery_days', models.PositiveSmallIntegerField(default=3, verbose_name='حداکثر روز ارسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(default='zarinpal', max_length=50, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='کد مرجع درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('product_sku', models.CharField(max_length=50, verbose_name='کد محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
