# Generated by Django 4.2.27 on 2025-12-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('home_top', 'صفحه اصلی - بالا'), ('home_middle', 'صفحه اصلی - وسط'), ('home_bottom', 'صفحه اصلی - پایین'), ('sidebar', 'سایدبار'), ('shop_top', 'فروشگاه - بالا')], default='home_middle', max_length=20, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='نمایش در فوتر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_description', models.TextField(blank=True, verbose_name='توضیحات سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='فاوآیکون')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='تلفن ۲')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساپ')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='کلمات کلیدی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('button_text', models.CharField(blank=True, default='مشاهده', max_length=50, verbose_name='متن دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
